# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\NovelScrapy\qtui\BookStackWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookStackWidget(object):
    def setupUi(self, BookStackWidget):
        BookStackWidget.setObjectName("BookStackWidget")
        BookStackWidget.resize(610, 610)
        BookStackWidget.setMinimumSize(QtCore.QSize(610, 610))
        BookStackWidget.setMaximumSize(QtCore.QSize(610, 610))
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(BookStackWidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.picNovelLabel = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel.setText("")
        self.picNovelLabel.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel.setObjectName("picNovelLabel")
        self.verticalLayout.addWidget(self.picNovelLabel)
        self.novelTitleLabel = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel.setObjectName("novelTitleLabel")
        self.verticalLayout.addWidget(self.novelTitleLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.picNovelLabel_4 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_4.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_4.setText("")
        self.picNovelLabel_4.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_4.setObjectName("picNovelLabel_4")
        self.verticalLayout_4.addWidget(self.picNovelLabel_4)
        self.novelTitleLabel_4 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_4.setObjectName("novelTitleLabel_4")
        self.verticalLayout_4.addWidget(self.novelTitleLabel_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.picNovelLabel_5 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_5.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_5.setText("")
        self.picNovelLabel_5.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_5.setObjectName("picNovelLabel_5")
        self.verticalLayout_5.addWidget(self.picNovelLabel_5)
        self.novelTitleLabel_5 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_5.setObjectName("novelTitleLabel_5")
        self.verticalLayout_5.addWidget(self.novelTitleLabel_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.picNovelLabel_3 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_3.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_3.setText("")
        self.picNovelLabel_3.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_3.setObjectName("picNovelLabel_3")
        self.verticalLayout_3.addWidget(self.picNovelLabel_3)
        self.novelTitleLabel_3 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_3.setObjectName("novelTitleLabel_3")
        self.verticalLayout_3.addWidget(self.novelTitleLabel_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.picNovelLabel_2 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_2.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_2.setText("")
        self.picNovelLabel_2.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_2.setObjectName("picNovelLabel_2")
        self.verticalLayout_2.addWidget(self.picNovelLabel_2)
        self.novelTitleLabel_2 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_2.setObjectName("novelTitleLabel_2")
        self.verticalLayout_2.addWidget(self.novelTitleLabel_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.picNovelLabel_6 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_6.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_6.setText("")
        self.picNovelLabel_6.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_6.setObjectName("picNovelLabel_6")
        self.verticalLayout_6.addWidget(self.picNovelLabel_6)
        self.novelTitleLabel_6 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_6.setObjectName("novelTitleLabel_6")
        self.verticalLayout_6.addWidget(self.novelTitleLabel_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.picNovelLabel_7 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_7.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_7.setText("")
        self.picNovelLabel_7.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_7.setObjectName("picNovelLabel_7")
        self.verticalLayout_7.addWidget(self.picNovelLabel_7)
        self.novelTitleLabel_7 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_7.setObjectName("novelTitleLabel_7")
        self.verticalLayout_7.addWidget(self.novelTitleLabel_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.picNovelLabel_8 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_8.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_8.setText("")
        self.picNovelLabel_8.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_8.setObjectName("picNovelLabel_8")
        self.verticalLayout_8.addWidget(self.picNovelLabel_8)
        self.novelTitleLabel_8 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_8.setObjectName("novelTitleLabel_8")
        self.verticalLayout_8.addWidget(self.novelTitleLabel_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.picNovelLabel_9 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_9.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_9.setText("")
        self.picNovelLabel_9.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_9.setObjectName("picNovelLabel_9")
        self.verticalLayout_9.addWidget(self.picNovelLabel_9)
        self.novelTitleLabel_9 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_9.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_9.setObjectName("novelTitleLabel_9")
        self.verticalLayout_9.addWidget(self.novelTitleLabel_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.picNovelLabel_10 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_10.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_10.setText("")
        self.picNovelLabel_10.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_10.setObjectName("picNovelLabel_10")
        self.verticalLayout_10.addWidget(self.picNovelLabel_10)
        self.novelTitleLabel_10 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_10.setObjectName("novelTitleLabel_10")
        self.verticalLayout_10.addWidget(self.novelTitleLabel_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.picNovelLabel_11 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_11.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_11.setText("")
        self.picNovelLabel_11.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_11.setObjectName("picNovelLabel_11")
        self.verticalLayout_11.addWidget(self.picNovelLabel_11)
        self.novelTitleLabel_11 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_11.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_11.setObjectName("novelTitleLabel_11")
        self.verticalLayout_11.addWidget(self.novelTitleLabel_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.picNovelLabel_12 = QtWidgets.QLabel(BookStackWidget)
        self.picNovelLabel_12.setMaximumSize(QtCore.QSize(130, 150))
        self.picNovelLabel_12.setText("")
        self.picNovelLabel_12.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.picNovelLabel_12.setObjectName("picNovelLabel_12")
        self.verticalLayout_12.addWidget(self.picNovelLabel_12)
        self.novelTitleLabel_12 = QtWidgets.QLabel(BookStackWidget)
        self.novelTitleLabel_12.setAlignment(QtCore.Qt.AlignCenter)
        self.novelTitleLabel_12.setObjectName("novelTitleLabel_12")
        self.verticalLayout_12.addWidget(self.novelTitleLabel_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        spacerItem18 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_4 = QtWidgets.QPushButton(BookStackWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(BookStackWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(BookStackWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(BookStackWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        spacerItem19 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem19)

        self.retranslateUi(BookStackWidget)
        QtCore.QMetaObject.connectSlotsByName(BookStackWidget)

    def retranslateUi(self, BookStackWidget):
        _translate = QtCore.QCoreApplication.translate
        BookStackWidget.setWindowTitle(_translate("BookStackWidget", "Form"))
        self.novelTitleLabel.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_4.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_5.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_3.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_2.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_6.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_7.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_8.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_9.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_10.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_11.setText(_translate("BookStackWidget", "牧神记"))
        self.novelTitleLabel_12.setText(_translate("BookStackWidget", "牧神记"))
        self.pushButton_4.setText(_translate("BookStackWidget", "首页"))
        self.pushButton_3.setText(_translate("BookStackWidget", "上一页"))
        self.pushButton_2.setText(_translate("BookStackWidget", "下一页"))
        self.pushButton.setText(_translate("BookStackWidget", "尾页"))

#import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BookStackWidget = QtWidgets.QWidget()
    ui = Ui_BookStackWidget()
    ui.setupUi(BookStackWidget)
    BookStackWidget.show()
    sys.exit(app.exec_())

