# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\NovelScrapy\qtui\indexWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IndexWidget(object):
    def setupUi(self, IndexWidget):
        IndexWidget.setObjectName("IndexWidget")
        IndexWidget.resize(587, 618)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(IndexWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.authorComBox = QtWidgets.QComboBox(IndexWidget)
        self.authorComBox.setObjectName("authorComBox")
        self.authorComBox.addItem("")
        self.authorComBox.addItem("")
        self.horizontalLayout.addWidget(self.authorComBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.authorLineEdit = QtWidgets.QLineEdit(IndexWidget)
        self.authorLineEdit.setObjectName("authorLineEdit")
        self.horizontalLayout.addWidget(self.authorLineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.novelSourceLabel = QtWidgets.QLabel(IndexWidget)
        self.novelSourceLabel.setObjectName("novelSourceLabel")
        self.horizontalLayout.addWidget(self.novelSourceLabel)
        self.novelSourceComBox = QtWidgets.QComboBox(IndexWidget)
        self.novelSourceComBox.setObjectName("novelSourceComBox")
        self.novelSourceComBox.addItem("")
        self.novelSourceComBox.addItem("")
        self.novelSourceComBox.addItem("")
        self.horizontalLayout.addWidget(self.novelSourceComBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.startBtn = QtWidgets.QPushButton(IndexWidget)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.novelPicLabel = QtWidgets.QLabel(IndexWidget)
        self.novelPicLabel.setMaximumSize(QtCore.QSize(140, 200))
        self.novelPicLabel.setText("")
        self.novelPicLabel.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.novelPicLabel.setObjectName("novelPicLabel")
        self.horizontalLayout_3.addWidget(self.novelPicLabel)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.novelUpateDateLabel = QtWidgets.QLabel(IndexWidget)
        self.novelUpateDateLabel.setObjectName("novelUpateDateLabel")
        self.gridLayout.addWidget(self.novelUpateDateLabel, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(IndexWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.novelNowChapterLabel = QtWidgets.QLabel(IndexWidget)
        self.novelNowChapterLabel.setObjectName("novelNowChapterLabel")
        self.gridLayout.addWidget(self.novelNowChapterLabel, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(IndexWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(IndexWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.author = QtWidgets.QLabel(IndexWidget)
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(IndexWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.addBookStackBtn = QtWidgets.QPushButton(IndexWidget)
        self.addBookStackBtn.setObjectName("addBookStackBtn")
        self.gridLayout.addWidget(self.addBookStackBtn, 1, 3, 1, 1)
        self.noveUnderlineLabel = QtWidgets.QLabel(IndexWidget)
        self.noveUnderlineLabel.setObjectName("noveUnderlineLabel")
        self.gridLayout.addWidget(self.noveUnderlineLabel, 3, 0, 1, 4)
        self.novelSmmary = QtWidgets.QTextEdit(IndexWidget)
        self.novelSmmary.setObjectName("novelSmmary")
        self.gridLayout.addWidget(self.novelSmmary, 4, 0, 1, 4)
        self.novelTitleLabel = QtWidgets.QLabel(IndexWidget)
        self.novelTitleLabel.setScaledContents(False)
        self.novelTitleLabel.setOpenExternalLinks(False)
        self.novelTitleLabel.setObjectName("novelTitleLabel")
        self.gridLayout.addWidget(self.novelTitleLabel, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.novelPicLabel_2 = QtWidgets.QLabel(IndexWidget)
        self.novelPicLabel_2.setMaximumSize(QtCore.QSize(140, 200))
        self.novelPicLabel_2.setText("")
        self.novelPicLabel_2.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.novelPicLabel_2.setObjectName("novelPicLabel_2")
        self.horizontalLayout_5.addWidget(self.novelPicLabel_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.novelUpateDateLabel_2 = QtWidgets.QLabel(IndexWidget)
        self.novelUpateDateLabel_2.setObjectName("novelUpateDateLabel_2")
        self.gridLayout_2.addWidget(self.novelUpateDateLabel_2, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(IndexWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.novelNowChapterLabel_2 = QtWidgets.QLabel(IndexWidget)
        self.novelNowChapterLabel_2.setObjectName("novelNowChapterLabel_2")
        self.gridLayout_2.addWidget(self.novelNowChapterLabel_2, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(IndexWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(IndexWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.author_2 = QtWidgets.QLabel(IndexWidget)
        self.author_2.setObjectName("author_2")
        self.gridLayout_2.addWidget(self.author_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(IndexWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.addBookStackBtn_2 = QtWidgets.QPushButton(IndexWidget)
        self.addBookStackBtn_2.setObjectName("addBookStackBtn_2")
        self.gridLayout_2.addWidget(self.addBookStackBtn_2, 1, 3, 1, 1)
        self.noveUnderlineLabel_2 = QtWidgets.QLabel(IndexWidget)
        self.noveUnderlineLabel_2.setObjectName("noveUnderlineLabel_2")
        self.gridLayout_2.addWidget(self.noveUnderlineLabel_2, 3, 0, 1, 4)
        self.novelSmmary_2 = QtWidgets.QTextEdit(IndexWidget)
        self.novelSmmary_2.setObjectName("novelSmmary_2")
        self.gridLayout_2.addWidget(self.novelSmmary_2, 4, 0, 1, 4)
        self.novelTitleLabel_2 = QtWidgets.QLabel(IndexWidget)
        self.novelTitleLabel_2.setScaledContents(False)
        self.novelTitleLabel_2.setOpenExternalLinks(False)
        self.novelTitleLabel_2.setObjectName("novelTitleLabel_2")
        self.gridLayout_2.addWidget(self.novelTitleLabel_2, 0, 0, 1, 4)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(IndexWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(IndexWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(IndexWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(IndexWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(IndexWidget)
        QtCore.QMetaObject.connectSlotsByName(IndexWidget)

    def retranslateUi(self, IndexWidget):
        _translate = QtCore.QCoreApplication.translate
        IndexWidget.setWindowTitle(_translate("IndexWidget", "Form"))
        self.authorComBox.setItemText(0, _translate("IndexWidget", "作者"))
        self.authorComBox.setItemText(1, _translate("IndexWidget", "书名"))
        self.novelSourceLabel.setText(_translate("IndexWidget", "小说源："))
        self.novelSourceComBox.setItemText(0, _translate("IndexWidget", "笔趣阁"))
        self.novelSourceComBox.setItemText(1, _translate("IndexWidget", "新笔趣阁"))
        self.novelSourceComBox.setItemText(2, _translate("IndexWidget", "顶点小说"))
        self.startBtn.setText(_translate("IndexWidget", "开始"))
        self.novelUpateDateLabel.setText(_translate("IndexWidget", "2018-8-24 22:36:34"))
        self.label_9.setText(_translate("IndexWidget", "最后更新："))
        self.novelNowChapterLabel.setText(_translate("IndexWidget", "西土古人"))
        self.label_11.setText(_translate("IndexWidget", "最后章节："))
        self.label_7.setText(_translate("IndexWidget", "操作："))
        self.author.setText(_translate("IndexWidget", "宅猪"))
        self.label_5.setText(_translate("IndexWidget", "作者："))
        self.addBookStackBtn.setText(_translate("IndexWidget", "加入书架"))
        self.noveUnderlineLabel.setText(_translate("IndexWidget", "TextLabel"))
        self.novelSmmary.setHtml(_translate("IndexWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI,Lucida Grande,Helvetica,Arial,Microsoft YaHei,FreeSans,Arimo,Droid Sans,wenquanyi micro hei,Hiragino Sans GB,Hiragino Sans GB W3,FontAwesome,sans-serif\'; font-size:14px; color:#666666; background-color:#e9faff;\">       大墟的祖训说，天黑，别出门。大墟残老村的老弱病残们从江边捡到了一个婴儿，取名秦牧，含辛茹苦将他养大。这一天夜幕降临，黑暗笼罩大墟，秦牧走出了家门……做个春风中荡漾的反派吧！瞎子对他说。秦牧的反派之路，正在崛起！</span></p></body></html>"))
        self.novelTitleLabel.setText(_translate("IndexWidget", "牧神记"))
        self.novelUpateDateLabel_2.setText(_translate("IndexWidget", "2018-8-24 22:36:34"))
        self.label_10.setText(_translate("IndexWidget", "最后更新："))
        self.novelNowChapterLabel_2.setText(_translate("IndexWidget", "西土古人"))
        self.label_12.setText(_translate("IndexWidget", "最后章节："))
        self.label_8.setText(_translate("IndexWidget", "操作："))
        self.author_2.setText(_translate("IndexWidget", "宅猪"))
        self.label_6.setText(_translate("IndexWidget", "作者："))
        self.addBookStackBtn_2.setText(_translate("IndexWidget", "加入书架"))
        self.noveUnderlineLabel_2.setText(_translate("IndexWidget", "TextLabel"))
        self.novelSmmary_2.setHtml(_translate("IndexWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI,Lucida Grande,Helvetica,Arial,Microsoft YaHei,FreeSans,Arimo,Droid Sans,wenquanyi micro hei,Hiragino Sans GB,Hiragino Sans GB W3,FontAwesome,sans-serif\'; font-size:14px; color:#666666; background-color:#e9faff;\">       大墟的祖训说，天黑，别出门。大墟残老村的老弱病残们从江边捡到了一个婴儿，取名秦牧，含辛茹苦将他养大。这一天夜幕降临，黑暗笼罩大墟，秦牧走出了家门……做个春风中荡漾的反派吧！瞎子对他说。秦牧的反派之路，正在崛起！</span></p></body></html>"))
        self.novelTitleLabel_2.setText(_translate("IndexWidget", "牧神记"))
        self.pushButton_5.setText(_translate("IndexWidget", "首页"))
        self.pushButton_4.setText(_translate("IndexWidget", "上一页"))
        self.pushButton_3.setText(_translate("IndexWidget", "下一页"))
        self.pushButton_6.setText(_translate("IndexWidget", "尾页"))

#import images_qrc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndexWidget = QtWidgets.QWidget()
    ui = Ui_IndexWidget()
    ui.setupUi(IndexWidget)
    IndexWidget.show()
    sys.exit(app.exec_())

