# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\NovelScrapy\qtui\right.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RightWidget(object):
    def setupUi(self, RightWidget):
        RightWidget.setObjectName("RightWidget")
        RightWidget.resize(581, 688)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(RightWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.authorComBox = QtWidgets.QComboBox(RightWidget)
        self.authorComBox.setObjectName("authorComBox")
        self.authorComBox.addItem("")
        self.authorComBox.addItem("")
        self.horizontalLayout.addWidget(self.authorComBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.authorLineEdit = QtWidgets.QLineEdit(RightWidget)
        self.authorLineEdit.setObjectName("authorLineEdit")
        self.horizontalLayout.addWidget(self.authorLineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.novelSourceLabel = QtWidgets.QLabel(RightWidget)
        self.novelSourceLabel.setObjectName("novelSourceLabel")
        self.horizontalLayout.addWidget(self.novelSourceLabel)
        self.novelSourceComBox = QtWidgets.QComboBox(RightWidget)
        self.novelSourceComBox.setObjectName("novelSourceComBox")
        self.novelSourceComBox.addItem("")
        self.novelSourceComBox.addItem("")
        self.novelSourceComBox.addItem("")
        self.horizontalLayout.addWidget(self.novelSourceComBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.startBtn = QtWidgets.QPushButton(RightWidget)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.novelPicLabel = QtWidgets.QLabel(RightWidget)
        self.novelPicLabel.setMaximumSize(QtCore.QSize(140, 200))
        self.novelPicLabel.setText("")
        self.novelPicLabel.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.novelPicLabel.setObjectName("novelPicLabel")
        self.horizontalLayout_3.addWidget(self.novelPicLabel)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(RightWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(RightWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(RightWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(RightWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(RightWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(RightWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(RightWidget)
        self.label.setScaledContents(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(RightWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(RightWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(RightWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(RightWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(RightWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(RightWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(RightWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.novelPicLabel_2 = QtWidgets.QLabel(RightWidget)
        self.novelPicLabel_2.setMaximumSize(QtCore.QSize(140, 200))
        self.novelPicLabel_2.setText("")
        self.novelPicLabel_2.setPixmap(QtGui.QPixmap(":/images/images/mushenji.jpg"))
        self.novelPicLabel_2.setObjectName("novelPicLabel_2")
        self.horizontalLayout_5.addWidget(self.novelPicLabel_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(RightWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(RightWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(RightWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(RightWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(RightWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(RightWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(RightWidget)
        self.label_2.setScaledContents(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(RightWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(RightWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(RightWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 4, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(RightWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 4, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(RightWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(RightWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(RightWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 4, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(RightWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(RightWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(RightWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(RightWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(RightWidget)
        QtCore.QMetaObject.connectSlotsByName(RightWidget)

    def retranslateUi(self, RightWidget):
        _translate = QtCore.QCoreApplication.translate
        RightWidget.setWindowTitle(_translate("RightWidget", "Form"))
        self.authorComBox.setItemText(0, _translate("RightWidget", "作者"))
        self.authorComBox.setItemText(1, _translate("RightWidget", "书名"))
        self.novelSourceLabel.setText(_translate("RightWidget", "小说源："))
        self.novelSourceComBox.setItemText(0, _translate("RightWidget", "笔趣阁"))
        self.novelSourceComBox.setItemText(1, _translate("RightWidget", "新笔趣阁"))
        self.novelSourceComBox.setItemText(2, _translate("RightWidget", "顶点小说"))
        self.startBtn.setText(_translate("RightWidget", "开始"))
        self.label_11.setText(_translate("RightWidget", "最后章节："))
        self.label_10.setText(_translate("RightWidget", "2018-8-24 22:36:34"))
        self.label_12.setText(_translate("RightWidget", "西土古人"))
        self.label_9.setText(_translate("RightWidget", "最后更新："))
        self.label_6.setText(_translate("RightWidget", "宅猪"))
        self.label_7.setText(_translate("RightWidget", "操作："))
        self.label.setText(_translate("RightWidget", "牧神记"))
        self.label_5.setText(_translate("RightWidget", "作者："))
        self.label_18.setText(_translate("RightWidget", "TextLabel"))
        self.label_19.setText(_translate("RightWidget", "TextLabel"))
        self.label_20.setText(_translate("RightWidget", "TextLabel"))
        self.pushButton.setText(_translate("RightWidget", "加入书架"))
        self.label_16.setText(_translate("RightWidget", "TextLabel"))
        self.label_13.setText(_translate("RightWidget", "最后章节："))
        self.label_14.setText(_translate("RightWidget", "2018-8-24 22:36:34"))
        self.label_15.setText(_translate("RightWidget", "西土古人"))
        self.label_17.setText(_translate("RightWidget", "最后更新："))
        self.label_8.setText(_translate("RightWidget", "宅猪"))
        self.label_21.setText(_translate("RightWidget", "操作："))
        self.label_2.setText(_translate("RightWidget", "牧神记"))
        self.label_22.setText(_translate("RightWidget", "作者："))
        self.label_23.setText(_translate("RightWidget", "TextLabel"))
        self.label_24.setText(_translate("RightWidget", "TextLabel"))
        self.label_25.setText(_translate("RightWidget", "TextLabel"))
        self.pushButton_2.setText(_translate("RightWidget", "加入书架"))
        self.label_26.setText(_translate("RightWidget", "TextLabel"))
        self.pushButton_5.setText(_translate("RightWidget", "首页"))
        self.pushButton_4.setText(_translate("RightWidget", "上一页"))
        self.pushButton_3.setText(_translate("RightWidget", "下一页"))
        self.pushButton_6.setText(_translate("RightWidget", "尾页"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RightWidget = QtWidgets.QWidget()
    ui = Ui_RightWidget()
    ui.setupUi(RightWidget)
    RightWidget.show()
    sys.exit(app.exec_())

